replicaCount: 1

image:
  repository: ghcr.io/shrutsharma958/integration-aggregator
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

openbao:
  address: "http://openbao:8200"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: 8080

readinessProbe:
  httpGet:
    path: /readyz
    port: 8080